# 병합/분리
- 배열을 합치거나 나누는 기능 정리임
- shape 조건 확인이 중요함


In [1]:
import numpy as np

## 요소 삽입/삭제
- `np.insert()`: 지정 위치에 값 삽입함
- `np.delete()`: 지정 위치의 값 삭제함
- 원본 배열을 직접 바꾸지 않고 새 배열 반환함


In [8]:
# np.insert(ndarray, index, elems, axis)
# - 지정된 elems를 삽입한 '새 배열'이 반환 == 원본이 별도로 유지됨!
arr = np.arange(1,13).reshape(3,4)  # 1부터 13 미만까지 숫자를 순서대로 나열하고 이를 3행 4열로 생성
arr

# axis = 0(행방향) 단위 삽입(insert)
# == 행 삽입
# - 삽입할 행의 열 개수는 삽입 대상 ndarray의 열 개수와 일치해야 한다.
np.insert(arr,1,[50,50,50,50], axis=0) # 행 1번 인덱스에 값이 들어감
np.insert(arr,2,[70], axis=0)   # 브로드캐스팅 적용됨: [70] -> [70,70,70,70]으로 변환

np.insert(arr, 1, 90, axis=0)

array([[ 1,  2,  3,  4],
       [90, 90, 90, 90],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
# arr
# axis = 1 == 열 (방향) 삽입
print(arr)
print(np.insert(arr,2,[50,50,50], axis=1))
print(np.insert(arr,2,[70], axis=1))
print(np.insert(arr,2, 70, axis=1))
print(np.insert(arr,2, 70, axis=None))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2 50  3  4]
 [ 5  6 50  7  8]
 [ 9 10 50 11 12]]
[[ 1  2 70  3  4]
 [ 5  6 70  7  8]
 [ 9 10 70 11 12]]
[[ 1  2 70  3  4]
 [ 5  6 70  7  8]
 [ 9 10 70 11 12]]
[ 1  2 70  3  4  5  6  7  8  9 10 11 12]


In [22]:
# delete (ndarray, index, axis)

print(arr)
print(np.delete(arr,2, axis = 0))    # 이것 또한 새로운 배열을 반환 == 원본은 별도로 유지됨
print(np.delete(arr,2, axis = 1))

# axis = None -> 1차원으로 변형 후 지정된 인덱스에 값 삭제
print(np.delete(arr,3, axis = None))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2  4]
 [ 5  6  8]
 [ 9 10 12]]
[ 1  2  3  5  6  7  8  9 10 11 12]


## 병합
- `np.append()`: 배열 뒤에 값 또는 배열 추가함
- `np.vstack()`: 세로 방향 병합함
- `np.hstack()`: 가로 방향 병합함
- `np.concatenate()`: 지정 axis 기준 병합함
- `np.column_stack()`: 배열을 열 기준으로 결합함


### np.append()
- 배열 뒤에 값을 추가함
- `axis=None`이면 1차원으로 펼쳐 붙임
- `axis=0/1` 지정 시 shape 조건 필요함


In [24]:
# 병합 함수는 shape 조건이 맞아야만 수행 가능

arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)

print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [26]:
print("np.append(arr1,arr2,axis=0")
print(np.append(arr1,arr2,axis=0))  # 행 순서 방향으로 병합

print("np.append(arr1,arr2,axis=1")
print(np.append(arr1,arr2,axis=1))  # 열 순서 방향으로 병합

print("np.append(arr1,arr2,axis=None")
print(np.append(arr1,arr2,axis=None))  # 전체를 1차원으로 바꾼 후 병합

np.append(arr1,arr2,axis=0
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
np.append(arr1,arr2,axis=1
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
np.append(arr1,arr2,axis=None
[ 1  2  3  4  5  6  7  8  9 10 11 12]


### np.vstack()
- vertical stack의 약자임
- 세로 방향으로 쌓음
- `axis=0` 방향 병합과 유사함
- 열 개수가 같아야 함


In [27]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### np.hstack()
- horizontal stack의 약자임
- 가로 방향으로 붙임
- `axis=1` 방향 병합과 유사함
- 행 개수가 같아야 함


In [ ]:
print(np.hstack((arr1, arr2)))
np.hstack((arr2, arr1))

### np.concatenate()
- 가장 일반적인 배열 연결 함수임
- `axis=0`: 아래로 붙
- `axis=1`: 옆으로 붙
- `axis=None`: 1차원으로 펼쳐 붙


In [34]:
# np.concatenate((arr1, arr2), axis=0)
# np.concatenate((arr1, arr2), axis=1)
np.concatenate((arr1, arr2), axis=None)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### np.column_stack()
- 1차원 배열을 열로 세워 결합함
- 여러 feature를 표 형태로 묶을 때 유용함


In [36]:
# np.column_stack(tuple)
# - 1차원 배열들을 열로 묶어서 2차원 배열처럼 만들어줌
a = np.array([1,2,3])   # (3,)
b = np.array([4,5,6])   # (3,)
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

## 분할
- `np.vsplit()`: 세로 방향 분할함
- `np.hsplit()`: 가로 방향 분할함
- 나누는 개수가 행/열 개수와 맞아야 함


In [39]:
arr = np.arange(1,25).reshape(6,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


### np.vsplit()
- vertical split의 약자임
- 행 기준으로 배열을 나눔
- 행 개수가 나누는 개수로 정확히 나뉘어야 함


In [40]:
# 분할할 수는 행 방향 == 행의 약수 (6,3,2,1)
# 분할할 수는 열 방향 == 열의 약수 (4,2,1)

print("np.vsplit(arr, 6)")
print(np.vsplit(arr, 6))

print("np.vsplit(arr, 3)")
print(np.vsplit(arr, 3))

np.vsplit(arr, 6)
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]]), array([[13, 14, 15, 16]]), array([[17, 18, 19, 20]]), array([[21, 22, 23, 24]])]
np.vsplit(arr, 3)
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]]), array([[17, 18, 19, 20],
       [21, 22, 23, 24]])]


### np.hsplit()
- horizontal split의 약자임
- 열 기준으로 배열을 나눔
- 열 개수가 나누는 개수로 정확히 나뉘어야 함


In [41]:
print("np.hsplit(arr, 4)")
print(np.hsplit(arr, 4))

print("np.hsplit(arr, 2)")
print(np.hsplit(arr, 2))

np.hsplit(arr, 4)
[array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17],
       [21]]), array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]]), array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23]]), array([[ 4],
       [ 8],
       [12],
       [16],
       [20],
       [24]])]
np.hsplit(arr, 2)
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])]
