In [4]:
import numpy as np

1. *크기가 2x2인 정규 분포로 구성된 배열*

NumPy를 사용하여 다음과 같은 배열을 생성해 보세요.

1. 크기가 4x3인 모든 값이 0인 배열
2. 크기가 3x3인 모든 값이 1인 배열
3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열
4. 0과 1 사이의 4개의 등간격 값을 가진 배열

In [7]:
arr1 = np.zeros((4,3))
print(arr1)
print("-"*50)
arr2 = np.ones((3,3))
print(arr2)
print("-"*50)
arr3 = np.arange(0,21,5)
print(arr3)
print("-"*50)
arr4 = np.linspace(0,1,4)
print(arr4)
print("-"*50)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
--------------------------------------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
--------------------------------------------------
[ 0  5 10 15 20]
--------------------------------------------------
[0.         0.33333333 0.66666667 1.        ]
--------------------------------------------------


1. 배열 `arr`에서 1번째 열만 추출
2. 배열 `arr`에서 2번째 행, 3번째 열의 값을 출력
3. 배열 `arr`에서 첫 번째 행부터 두 번째 행까지 선택하고, 0번째와 1번째 열만 추출
```arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])```

In [14]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

arr1 = arr[:,1]
print(arr1)
print("-"*50)

arr2 = arr[1,2]
print(arr2)
print("-"*50)

arr3 = arr[:2,:2]
print(arr3)

[20 50 80]
--------------------------------------------------
60
--------------------------------------------------
[[10 20]
 [40 50]]


아래 배열에서 팬시 인덱싱과 불리언 인덱싱을 사용하여 다음 작업을 수행하세요.

1. 팬시 인덱싱을 사용하여 배열의 0번째, 2번째, 4번째 요소를 출력
2. 배열의 값 중 50보다 큰 값만 추출

```	arr = np.array([10, 20, 30, 40, 50, 60, 70])```

In [16]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

arr1 = arr[[0,2,4]]
print(arr1)

[10 30 50]


어느 마트에서 판매되는 제품들의 월별 매출량이 아래와 같이 주어졌습니다. 각각의 행은 제품을 나타내고, 열은 각 월의 판매량을 나타냅니다.

1. 월별 판매량이 200개 이상인 제품의 판매량을 선택하라.
2. 3월(세 번째 열)의 판매량이 100개 이하인 제품의 1월과 2월 판매량을 추출하라.
3. 2월(두 번째 열)의 판매량이 150개 이상인 제품들의 전체 월별 판매량을 출력하라.

```
sales = np.array([[120, 150, 100],
                  [80, 90, 110],
                  [200, 180, 220],
                  [50, 45, 70],
                  [300, 320, 310]])
```

In [26]:
sales = np.array([[120, 150, 100],
                  [80, 90, 110],
                  [200, 180, 220],
                  [50, 45, 70],
                  [300, 320, 310]])

arr1 = sales[sales >=200]
print(arr1)
print("-"*50)

arr2 = sales[sales[:,2] <= 100]
arr3 = arr2[:2,:2]
print(arr3)
print("-"*50)

arr4 = sales[sales[:,1] >= 150]
print(arr4)

[200 220 300 320 310]
--------------------------------------------------
[[120 150]
 [ 50  45]]
--------------------------------------------------
[[120 150 100]
 [200 180 220]
 [300 320 310]]


다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.

1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
2. 과일별 평균 판매량을 구하세요.

- **데이터**:
    - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
    - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)

In [35]:
first_q = np.array([200,340,150,400])
second_q = np.array([220,300,180,420])

sum = first_q + second_q
print(sum.sum())
print("-"*50)

mean = (first_q + second_q) / 2
print(mean)

2210
--------------------------------------------------
[210. 320. 165. 410.]


다음 두 배열을 사용하여 각각의 요소별로 덧셈, 뺄셈, 곱셈, 나눗셈을 수행하세요.

```
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])
```

In [38]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

sum = arr1 + arr2
minus = arr1 - arr2
multiple = arr1 * arr2
division = arr1 / arr2
print(sum)
print(minus)
print(multiple)
print(division)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


다음 두 배열 간의 내적 연산을 수행하세요.
```
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
```

In [43]:
print(arr1 @ arr2)

300


아래의 2차원 배열과 1차원 배열을 브로드캐스팅하여 더하세요.
```
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])
```

In [45]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])

arr2d + arr1d

array([[11, 22, 33],
       [14, 25, 36]])

1. 배열에서 20보다 큰 값을 찾아 출력하세요.
2. 배열의 합계, 최대값, 최소값, 평균을 계산하세요.
```
arr = np.array([10, 20, 30, 40, 50])
```

In [52]:
arr = np.array([10, 20, 30, 40, 50])
arr1 = arr[arr>20]
print(arr1)

sum=arr1.sum()
max = arr1.max()
min = arr1.min()
mean = arr1.mean()

print(sum)
print(max)
print(min)
print(mean)

[30 40 50]
120
50
30
40.0


아래 배열에서 평균, 중앙값, 최빈값, 분산, 표준편차, 범위를 계산하세요.
```
arr = np.array([10, 20, 30, 30, 40, 50, 60])
```

In [77]:
arr = np.array([10, 20, 30, 30, 40, 50, 60])

mean = arr.mean()
print("평균:", mean)
center = arr[::1]
print(round(len(center)/2))
print("중앙값:", center[round(len(center)/2)-1])

from scipy import stats
most = stats.mode(arr)
print("최빈값:",most.mode)

var = np.var(arr)
print("분산:",var)

std = np.std(arr)
print("표준편차:", std)

평균: 34.285714285714285
4
중앙값: 30
최빈값: 30
분산: 253.06122448979593
표준편차: 15.90789817951435


정규분포와 균등분포에서 각각 난수를 생성하여, 평균과 표준편차를 계산하세요.

1. 평균 0, 표준편차 1인 정규분포 난수 1000개 생성
2. 0과 1 사이의 균등분포 난수 1000개 생성

In [100]:
gen = np.random.randn(1000)
# print(gen)
avg = gen.mean()
print("평균:", avg)

same = np.random.uniform(0,1,1000)
print(same)

평균: -0.026272852540702652
[8.83780945e-02 3.00779871e-01 2.36024953e-01 1.80849520e-01
 4.75881060e-01 7.25114506e-02 5.99039270e-01 5.01912486e-01
 9.92250749e-02 5.89196518e-01 1.46414322e-01 9.96904500e-02
 8.51083761e-01 3.41096845e-01 4.40803860e-01 2.48799010e-02
 7.84406074e-01 1.92325424e-01 5.87166198e-02 9.78780944e-01
 5.90729308e-01 2.68420423e-01 4.26207259e-01 4.93981334e-01
 1.58472794e-01 2.16557271e-01 7.45949434e-01 3.34494244e-01
 7.98019886e-01 6.62234238e-01 9.91437472e-02 6.19214348e-01
 6.50065523e-02 3.41533448e-01 4.32148797e-01 3.43324541e-01
 1.48421586e-01 4.57914307e-01 5.72348427e-01 6.45412120e-01
 6.30963935e-01 2.38373508e-01 5.22740224e-01 5.61625764e-01
 3.21633679e-01 2.12302023e-01 4.66681953e-01 8.66051143e-01
 8.56162069e-01 3.13676145e-01 6.68062146e-01 9.76634825e-02
 2.29256133e-01 9.30932538e-01 5.55481397e-01 6.48763958e-01
 6.32103133e-01 4.43531528e-01 8.59704151e-01 3.13899401e-01
 4.39479453e-01 5.68353801e-01 5.68152205e-01 1.39697118e-0

[실습 3] 평균 성적 구하기

아래와 같이 학생별 과목 성적 데이터가 주어졌을 때, 각 학생의 전체 평균 성적(수학, 영어, 과학)을 계산한 후, 이 평균값에 대한 분산과 표준편차를 구하세요.

```python
# 학생별 과목 성적 데이터
scores_math = [88, 92, 76, 85, 95, 92, 88, 90, 85, 88]
scores_english = [90, 85, 80, 87, 92, 89, 83, 91, 86, 88]
scores_science = [85, 88, 82, 89, 94, 86, 91, 88, 84, 87]
```

In [109]:
scores_math = [88, 92, 76, 85, 95, 92, 88, 90, 85, 88]
scores_english = [90, 85, 80, 87, 92, 89, 83, 91, 86, 88]
scores_science = [85, 88, 82, 89, 94, 86, 91, 88, 84, 87]

avg_math = np.mean(scores_math)
avg_english = np.mean(scores_english)
avg_scores_science = np.mean(scores_science)

print(avg_math,avg_english,avg_scores_science)


var_math = np.var(scores_math)
var_english = np.var(scores_english)
var_science = np.var(scores_science)

std_math =np.std(scores_math)
std_english =np.std(scores_english)
std_science = np.std(scores_science)

print(var_math,var_english,var_science)
print(std_math,std_english,std_science)

87.9 87.1 87.4
24.689999999999994 12.49 10.84
4.968903299521937 3.5341194094144583 3.2924155266308657


 # Numpy: 정렬
 다음 1차원 배열을 오름차순 및 내림차순으로 정렬하세요.
 ```
arr = np.array([50, 10, 30, 40, 20])
```

In [9]:
arr = np.array([50, 10, 30, 40, 20])

arr1 = np.sort(arr)
arr2 = arr1[::-1]

print(arr1)
print(arr2)

[10 20 30 40 50]
[50 40 30 20 10]


다음 2차원 배열을 행과 열을 기준으로 각각 정렬하세요.
```
arr2d = np.array([[8, 3, 5], [2, 9, 1]])
```

In [11]:
arr2d = np.array([[8, 3, 5], [2, 9, 1]])

arr1 = np.sort(arr2d, axis=0)
arr2 = np.sort(arr2d, axis=1)

print(arr2d)
print(arr1)
print(arr2)

[[8 3 5]
 [2 9 1]]
[[2 3 1]
 [8 9 5]]
[[3 5 8]
 [1 2 9]]


다음 1차원 배열에서 정렬된 결과의 인덱스를 반환하고, 그 인덱스를 사용하여 배열을 정렬하세요.
```
arr = np.array([15, 10, 20])
```

In [13]:
arr = np.array([15, 10, 20])

order = np.argsort(arr)
print(order)
print(arr[order])

[1 0 2]
[10 15 20]


# Numpy: 병합
다음 두 개의 1차원 배열을 np.concatenate()와 np.hstack()을 사용하여 병합하세요.
```
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
```

In [36]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2), axis = 0)
print(arr)

arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


다음 두 개의 2차원 배열을 np.concatenate()와 np.vstack()을 사용하여 각각 병합하세요.

```
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
```

In [35]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis = 0)
print(arr)

arr = np.vstack((arr1,arr2))
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# [7] Numpy 종합 실습

### 다음은 5개 지점에서 판매된 과일에 대한 월별 판매량 데이터입니다. 이 데이터는 각 지점의 판매량을 월별로 나타내며, 각 지점에서 판매된 사과, 바나나, 오렌지의 판매량이 기록되어 있습니다. 이 데이터를 사용하여 여러 가지 통계적 분석과 배열 조작을 수행하세요.

1. 각 지점에서 6개월 동안 판매된 **사과**, **바나나**, **오렌지**의 월별 평균 판매량을 계산하세요.
2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
3. 6개월 동안 전체 지점에서 가장 많이 판매된 과일의 총량을 과일별로 구하세요. 어떤 과일이 가장 많이 판매되었는지 확인하세요.
4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.

```
import numpy as np

# 5개 지점의 월별 사과, 바나나, 오렌지 판매량 (5x3x6 배열)
# 5개의 지점, 3개의 과일(사과, 바나나, 오렌지), 6개월치 데이터
sales_data = np.array([
    # 지점 1
    [[120, 150, 200, 230, 180, 210],  # 사과 판매량
     [100, 140, 170, 190, 160, 180],  # 바나나 판매량
     [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량

    # 지점 2
    [[80, 90, 110, 140, 130, 120],
     [60, 70, 90, 100, 110, 95],
     [50, 80, 100, 110, 90, 85]],

    # 지점 3
    [[130, 140, 160, 180, 170, 190],
     [110, 120, 130, 150, 140, 160],
     [100, 110, 120, 130, 120, 140]],

    # 지점 4
    [[100, 130, 150, 170, 160, 180],
     [90, 100, 110, 120, 130, 125],
     [80, 110, 140, 130, 120, 110]],

    # 지점 5
    [[90, 110, 130, 140, 120, 130],
     [70, 85, 100, 110, 105, 95],
     [60, 90, 110, 100, 90, 95]]
])
```

In [38]:
import numpy as np

# 5개 지점의 월별 사과, 바나나, 오렌지 판매량 (5x3x6 배열)
# 5개의 지점, 3개의 과일(사과, 바나나, 오렌지), 6개월치 데이터
sales_data = np.array([
    # 지점 1
    [[120, 150, 200, 230, 180, 210],  # 사과 판매량
     [100, 140, 170, 190, 160, 180],  # 바나나 판매량
     [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량

    # 지점 2
    [[80, 90, 110, 140, 130, 120],
     [60, 70, 90, 100, 110, 95],
     [50, 80, 100, 110, 90, 85]],

    # 지점 3
    [[130, 140, 160, 180, 170, 190],
     [110, 120, 130, 150, 140, 160],
     [100, 110, 120, 130, 120, 140]],

    # 지점 4
    [[100, 130, 150, 170, 160, 180],
     [90, 100, 110, 120, 130, 125],
     [80, 110, 140, 130, 120, 110]],

    # 지점 5
    [[90, 110, 130, 140, 120, 130],
     [70, 85, 100, 110, 105, 95],
     [60, 90, 110, 100, 90, 95]]
])

In [129]:
lst =[]

for i in range(len(sales_data)):
    mean_apple = np.mean(sales_data[i][0])
    mean_banana = np.mean(sales_data[i][1])
    mean_orange = np.mean(sales_data[i][2])
    lst.append([mean_apple, mean_banana, mean_orange])

print(np.array(lst))

[[181.66666667 156.66666667 131.66666667]
 [111.66666667  87.5         85.83333333]
 [161.66666667 135.         120.        ]
 [148.33333333 112.5        115.        ]
 [120.          94.16666667  90.83333333]]


In [155]:
lst_apple =[]
lst_banana =[]
lst_orange =[]
lst = sales_data[:, :, :]
lst = lst.reshape(-1, 1)
cnt = 0
n = 1


for i in lst:
    if n in (1,4,7,10,13) and cnt < 6 * n:
        lst_apple.append(i)
        cnt += 1
        if cnt == 6 * n:
            n += 1
    elif n in (2,5,8,11,14) and cnt < 6 * n:
        lst_banana.append(i)
        cnt += 1
        if cnt == 6 * n:
            n += 1
    elif n in (3,6,9,12,15) and cnt < 6 * n:
        lst_orange.append(i)
        cnt += 1
        if cnt == 6 * n:
            n += 1




lst_apple = np.sum(lst_apple)
lst_banana = np.sum(lst_banana)
lst_orange = np.sum(lst_orange)

# print("사과:", lst_apple)
# print("바나나:", lst_banana)
# print("오렌지", lst_orange)

num = [lst_apple, lst_banana, lst_orange]
max = np.argmax(num)

if max == 0:
    print("사과:", lst_apple)
elif max == 1:
    print("바나나:", lst_banana)
elif max == 2:
    print("오렌지:", lst_orange)

사과: 4340


In [265]:
lst_space = []
lst = sales_data
lst = lst.reshape(-1, 1)
cnt = 0

for i in lst:
    if i >= 150:
        lst_space.append(cnt)
    cnt += 1

n = 1
for i in range(len(lst_space)):
    if lst_space[i] < 18:
        print("지점1")
    elif lst_space[i] < 36:
        print("지점2")
    elif lst_space[i] < 54:
        print("지점3")
    elif lst_space[i] < 72:
        print("지점4")
    elif lst_space[i] < 90:
        print("지점5")

    if lst_space[i] > 6 * n:
        n += 1


    if n in (1,4,7,10,13) and lst_space[i] < 6 * n:
        print("사과")

    elif n in (2,5,8,11,14) and lst_space[i] < 6 * n:
        print("바나나")

    elif n in (3,6,9,12,15) and lst_space[i] < 6 * n:
        print("오렌지")


print(lst_space)

# print(lst_space[0]['2'])


지점1
사과
지점1
사과
지점1
사과
지점1
사과
지점1
사과
지점1
바나나
지점1
바나나
지점1
바나나
지점1
바나나
지점1
오렌지
지점1
오렌지
지점3
지점3
지점3
지점3
사과
지점3
바나나
지점3
바나나
지점4
지점4
사과
지점4
사과
지점4
사과
[1, 2, 3, 4, 5, 8, 9, 10, 11, 14, 17, 38, 39, 40, 41, 45, 47, 56, 57, 58, 59]
